### ISSUE TITLE
[DynamicShapes] Square gets bigger

### ISSUE THREAD

**Issue by nsnans** [khlebobul/gen_art_bg#1]
![PixPin_2024-11-08_17-53-34](https://github.com/user-attachments/assets/02d8b107-56ed-4118-951d-00d814e18756)

When the window switches, this will suddenly become larger, I'm not sure if this effect is what you expect, but it may feel a bit problematic.

```dart
        DynamicShapes(
          backgroundColor: Colors.greenAccent.withOpacity(.13),
          minShapeSize: MediaQuery.of(context).size.width < 1200 ? 0.01 : 0.001,
          maxShapeSize: MediaQuery.of(context).size.width < 1200 ? 0.05 : 0.01,
          colors: [
            BColors.bg,
            BColors.black50,
            BColors.body,
            BColors.selectBg,
            BColors.danger,
            BColors.primary,
            BColors.secondary,
            BColors.light,
            BColors.warning,
            BColors.success,
          ],
        ),
```

**Comment by khlebobul** [comment]
Hello @nsnans, thank you very much for your observation. Yes, you are right, it is quite a strange behavior. I will try to rectify this situation as soon as possible.

**Comment by nsnans** [comment]
@khlebobul appreciate your efforts.

**Comment by khlebobul** [comment]
@nsnans you're setting the sizes here

```dart
minShapeSize: MediaQuery.of(context).size.width < 1200 ? 0.01 : 0.001,
maxShapeSize: MediaQuery.of(context).size.width < 1200 ? 0.05 : 0.01,
```

In my example, the sizes are fixed

```dart
minShapeSize: 0.02, // min shape size
maxShapeSize: 0.08, // max shape size
```

**Comment by khlebobul** [comment]
https://github.com/user-attachments/assets/ae47d70e-208b-4eab-9c3a-83c1d76172c8

**Comment by nsnans** [comment]
> @nsnans you're setting the sizes here
> 
> ```dart
> minShapeSize: MediaQuery.of(context).size.width < 1200 ? 0.01 : 0.001,
> maxShapeSize: MediaQuery.of(context).size.width < 1200 ? 0.05 : 0.01,
> ```
> 
> In my example, the sizes are fixed
> 
> ```dart
> minShapeSize: 0.02, // min shape size
> maxShapeSize: 0.08, // max shape size
> ```

in my gif，When the window becomes larger, the block will suddenly become larger and then shrink to its normal size, which should not be related to this size change

**Comment by khlebobul** [comment]
Try using smooth scaling instead of abrupt switching

```dart
minShapeSize: 0.01 * (1200 / math.max(MediaQuery.of(context).size.width, 1200)),
maxShapeSize: 0.05 * (1200 / math.max(MediaQuery.of(context).size.width, 1200)),
```

**Comment by nsnans** [comment]
> Try using smooth scaling instead of abrupt switching
> 
> ```dart
> minShapeSize: 0.01 * (1200 / math.max(MediaQuery.of(context).size.width, 1200)),
> maxShapeSize: 0.05 * (1200 / math.max(MediaQuery.of(context).size.width, 1200)),
> ```

In China, it is now after work and I am unable to use the company's desktop computer to try the effect. Thank you for your answer

**Comment by khlebobul** [comment]
Not a problem, you can try it when it's convenient. My result ⬇️

https://github.com/user-attachments/assets/40f639d9-9606-489e-a785-e1d73c8f9706

The code

```dart
DynamicShapes(
        colors: const [Colors.blue, Colors.red, Colors.green],
        maxShapes: 150,
        minShapeSize:
            0.01 * (1200 / math.max(MediaQuery.of(context).size.width, 1200)),
        maxShapeSize:
            0.05 * (1200 / math.max(MediaQuery.of(context).size.width, 1200)),
        minActionPoints: 3,
        maxActionPoints: 6,
        animationSpeed: 1.5,
        backgroundColor: Colors.black,
      ),
```

Don't forget to add `import 'dart:math' as math;`
